#!/bin/bash

set -eo pipefail

version=$1

cd /tmp

if [ "$version" == "latest" ] ; then
	wget https://github.com/jiprolog/jiprolog/releases/download/v4.1.7.1/JIProlog-4.1.7.1.zip
	unzip JIProlog-4.1.7.1.zip
else
	wget https://github.com/jiprolog/jiprolog/releases/download/v$version/JIProlog-$version.zip
	unzip JIProlog-$version.zip
fi
cp JIProlog/jipconsole.jar "$GITHUB_WORKSPACE"
export CLASSPATH="$GITHUB_WORKSPACE/jipconsole.jar":"$CLASSPATH"
export JIP_HOME="$GITHUB_WORKSPACE"
