name: Test

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    timeout-minutes: 2
    steps:
      - name: Install JIProlog
        uses: logtalk-actions/setup-jiprolog@master
        with:
          jiprolog-version: 4.1.6.1
      - name: Run trivial sanity test
        env:
          DISPLAY: "localhost:0"
        run: java -jar -DLOGTALKHOME="/usr/local/logtalk" -DLOGTALKUSER="$HOME/logtalk" -DHOME="$HOME" jipconsole.jar -g halt
