name: Test

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    timeout-minutes: 2
    steps:
      - name: Set environment variables
        env:
          CLASSPATH: "$GITHUB_WORKSPACE/jipconsole.jar:$CLASSPATH"
          JIP_HOME: "$GITHUB_WORKSPACE"
      - name: Install JIProlog
        uses: logtalk-actions/setup-jiprolog@master
        with:
          jiprolog-version: 4.1.6.1
      - name: Run trivial sanity test
        run: |
          ls "$GITHUB_WORKSPACE"
          echo $CLASSPATH
          echo $JIP_HOME
          java -jar -DLOGTALKHOME="$LOGTALKHOME" -DLOGTALKUSER="$LOGTALKUSER" -DHOME="$HOME" "$JIP_HOME/jipconsole.jar" -g halt
